import type { Metadata } from "next";
import { Rethink_Sans, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});


const rethinkSans = Rethink_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Business Listing in India - Business Directory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" 
      className={cn("h-full", "antialiased", rethinkSans.variable, "font-sans")}
    >
      <body className="min-h-full">{children}</body>
    </html>
  );
}
